import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Load fonts
const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Arunava Mondal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Default font is Inter */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
